print("contact form")
print(" ")
Name=(input("Please enter your name:"))
print(" ")
Age=(input("Please enter your age:"))
print(" ")
Course=(input("Please select the course you are interested in:\n1)python development course \n2)data analysis with python \n3)Advance Data science \n"))
print(" ")
Contact=(input("Please enter your contact number:"))
print(" ")
print("entered details are\n")
print(f"The entered name is:{Name}\nThe entered age is:{Age}\nSelected course is: {Course}\nThe entered contact number is:{Contact}")
print(" ")
print(input("The above mentioned details are correct or not\n yes/no:"))
